name: doctorapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: any
  responsive_sizer: any
  carousel_slider: any
  image_picker: any
  motion_tab_bar: ^2.0.4
  flutter_otp_text_field: ^1.2.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Specify the assets path here
  assets:
    - assets/images/
